#!/usr/bin/env bash

SPRING_DATASOURCE_DRIVER="postgresql"
SPRING_DATASOURCE_HOST="host.docker.internal"
SPRING_DATASOURCE_PORT="5432"
SPRING_DATASOURCE_DATABASE="inaam"
SPRING_DATASOURCE_USERNAME="postgres"
SPRING_DATASOURCE_PASSWORD="postgres"
SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver"

docker build -t inaam .

docker container run -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="$SPRING_DATASOURCE_DRIVER_CLASS_NAME" -e SPRING_DATASOURCE_DRIVER="$SPRING_DATASOURCE_DRIVER" -e SPRING_DATASOURCE_HOST="$SPRING_DATASOURCE_HOST" -e SPRING_DATASOURCE_PORT="$SPRING_DATASOURCE_PORT" -e SPRING_DATASOURCE_DATABASE="$SPRING_DATASOURCE_DATABASE" -e SPRING_DATASOURCE_USERNAME="$SPRING_DATASOURCE_USERNAME" -e SPRING_DATASOURCE_PASSWORD="$SPRING_DATASOURCE_PASSWORD" -p 8080:8080 inaam